---
- name: Update and Upgrade all packages, then conditionally reboot
  hosts: ubuntuhosts
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      register: apt_upgrade

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      ignore_errors: true

    - name: Reboot the machine if required
      reboot:
        msg: "Rebooting due to system upgrade requirements"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime
      when: reboot_required.stat.exists == true

    - name: Wait for the machine to come back
      wait_for_connection:
        delay: 60
        timeout: 300
      when: reboot_required.stat.exists == true

    - name: Check uptime and kernel version
      command: "{{ item }}"
      loop:
        - uptime
        - uname -r
      register: system_info

    - name: Show uptime and kernel version
      debug:
        msg: "{{ item.stdout }}"
      loop: "{{ system_info.results }}"


