#!/usr/bin/env bash
#
# Harden-auditd for a set of local users.
# Usage (as root):  ./setup-audit.sh
#

set -euo pipefail

################################################################################
#USER_LIST="root userb usera userdupa"
USER_LIST=$(awk -F: '/\/(ba|z|tm)?sh$/ {print $1}' /etc/passwd)

################################################################################
# 2. Install auditd once                                                       #
################################################################################
echo "Installing and configuring auditd …"
if ! dpkg -s auditd &>/dev/null; then
    apt-get update
    apt-get install -y auditd
    echo "auditd installed."
else
    echo "auditd already present."
fi


################################################################################
for USERNAME in $USER_LIST; do
    # Skip unknown accounts (e.g. typo)
    if ! id "$USERNAME" &>/dev/null; then
        echo "User '$USERNAME' does not exist – skipping."
        continue
    fi

    USER_ID=$(id -u "$USERNAME")
    USER_HOME=$(eval echo "~$USERNAME")
    AUDIT_RULES_FILE="/etc/audit/rules.d/99-monitor-${USERNAME}.rules"

    echo " Writing audit rules to $AUDIT_RULES_FILE …"
    cat > "$AUDIT_RULES_FILE" <<EOF
# ---------------------------------------------------------------------------
# Audit rules for user $USERNAME  (UID $USER_ID)
# Generated by setup-audit.sh on $(date -Is)
# ---------------------------------------------------------------------------

# 1. Log every command executed by the user (execve syscall)
-a always,exit -F arch=b64 -S execve -F auid=$USER_ID -k user_exec_${USERNAME}
-a always,exit -F arch=b32 -S execve -F auid=$USER_ID -k user_exec_${USERNAME}

# 2. Watch the user’s home directory for writes & attribute changes
-w ${USER_HOME}/ -p wa -k user_home_change_${USERNAME}

EOF
    echo "Rules for $USERNAME written."
done


################################################################################
echo "🔄  Reloading auditd rule set …"
augenrules --load   # generates /etc/audit/audit.rules from *.rules
systemctl restart auditd
echo "auditd reloaded."

################################################################################
BASH_LOG_CONF="/etc/profile.d/bash_persistent_history.sh"
if [[ ! -f $BASH_LOG_CONF ]]; then
    echo "📝  Enabling persistent bash history logging …"
    cat > "$BASH_LOG_CONF" <<'EOF'
# Send every executed shell line to syslog (local6.debug)
export PROMPT_COMMAND='RETVAL=$?; logger -p local6.debug -- "$(whoami) [$$]: $(history 1 | sed "s/^[ ]*[0-9]\+[ ]*//")"'
EOF
    chmod +x "$BASH_LOG_CONF"
    echo "Bash history logging enabled."
else
    echo "Bash history logging already configured."
fi

echo "🎉 All done!  Your chosen users are now fully audited."
